
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: Natabar@143
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:  # Import configuration from the Config Server

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

product-service:
  messages: 
    productCreated: Product Created Successfully
    productCreationFailed: Product Creation Failed
    productUpdated: Product Updated Successfully
    productUpdateFailed: Product Update Failed
    productDeleted: Product Deleted Successfully
    productDeletionFailed: Product Deletion Failed
    productNotFound: Product Not Found
    productFetchError: Error Fetching Product
